CREATE TABLE Socios
(
  SocioID INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Apellido VARCHAR(50) NOT NULL,
  DNI INT NOT NULL,
  Calle VARCHAR(50) NOT NULL,
  Numero INT NOT NULL,
  PRIMARY KEY (SocioID)
);

CREATE TABLE Libros
(
  AnioEdicion INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  Titulo VARCHAR(50) NOT NULL,
  Editorial VARCHAR(50) NOT NULL,
  AnioEscritura INT NOT NULL,
  PRIMARY KEY (ISBN)
);

CREATE TABLE Volumenes
(
  EjemplarNumero INT NOT NULL,
  Deteriorado INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  PRIMARY KEY (ISBN),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
);

CREATE TABLE Prestamos
(
  Fecha DATE NOT NULL,
  FechaTope DATE NOT NULL,
  FechaDevolucion DATE NOT NULL,
  SocioID INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  PRIMARY KEY (SocioID, ISBN),
  FOREIGN KEY (SocioID) REFERENCES Socios(SocioID),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
);

CREATE TABLE Socio_Telefono
(
  Telefono VARCHAR(17) NOT NULL,
  SocioID INT NOT NULL,
  PRIMARY KEY (Telefono, SocioID),
  FOREIGN KEY (SocioID) REFERENCES Socios(SocioID)
);

CREATE TABLE Libro_Autor
(
  Autor INT NOT NULL,
  ISBN VARCHAR(17) NOT NULL,
  PRIMARY KEY (Autor, ISBN),
  FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
);