CREATE TABLE CLIENTES
(
  DNI INT NOT NULL,
  nombre VARCHAR(25) NOT NULL,
  PRIMARY KEY (DNI)
);

CREATE TABLE PRODUCTOS
(
  codigo INT NOT NULL,
  descripcion VARCHAR(50) NOT NULL,
  precio INT NOT NULL,
  DNI_cliente INT NOT NULL,
  PRIMARY KEY (codigo),
  FOREIGN KEY (DNI_cliente) REFERENCES CLIENTES(DNI)
);

CREATE TABLE CUOTAS
(
  nro_cuota INT NOT NULL,
  importe INT NOT NULL,
  fecha DATE NOT NULL,
  cod_producto INT NOT NULL,
  PRIMARY KEY (nro_cuota, cod_producto),
  FOREIGN KEY (cod_producto) REFERENCES PRODUCTOS(codigo)
);

CREATE TABLE TELEFONOS
(
  telefono VARCHAR(15) NOT NULL,
  DNI_cliente INT NOT NULL,
  PRIMARY KEY (telefono, DNI_cliente),
  FOREIGN KEY (DNI_cliente) REFERENCES CLIENTES(DNI)
);