//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int id { get; set; }
        public string Legajo { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public System.DateTime Nacimiento { get; set; }
    }
}
