ALTER DATABASE RJCodeAdvance SET EMERGENCY;
GO
ALTER DATABASE RJCodeAdvance set single_user
GO
DBCC CHECKDB (RJCodeAdvance, REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS;
GO
ALTER DATABASE RJCodeAdvance set multi_user
GO