//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoID { get; set; }
        public string ProductoNombre { get; set; }
        public decimal ProductoPrecio { get; set; }
        public string ProductoDescripcion { get; set; }
        public int ProductoProveedor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
